/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelProgress.java
 *
 * Created on Dec 2, 2010, 12:52:59 PM
 */

package com.jcl.utils;

/**
 *
 * @author jlavador
 */
public class JPanelSetupProgress extends javax.swing.JPanel {

    /** Creates new form JPanelProgress */
    public JPanelSetupProgress() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXBusyLabel1 = new org.jdesktop.swingx.JXBusyLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new java.awt.GridBagLayout());

        jXBusyLabel1.setText("Please wait, while starting up HJR Payroll System");
        jXBusyLabel1.setBusy(true);
        jXBusyLabel1.setDirection(org.jdesktop.swingx.JXBusyLabel.Direction.RIGHT);
        jXBusyLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXBusyLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jXBusyLabel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1;
    // End of variables declaration//GEN-END:variables

}
