/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubMaterialDialog.java
 *
 * Created on Nov 4, 2010, 8:57:16 AM
 */
package com.jcl.utils;

import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author jlavador
 */
public class MyJasperViewer extends javax.swing.JDialog {



    /** Creates new form SubMaterialDialog */
    public MyJasperViewer(java.awt.Frame parent, boolean modal, JRViewer jrv ) {
        super(parent, modal);
        initComponents();
        this.setSize(500, 500);
        this.panelJViewer.add(jrv);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelJViewer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail");
        setMinimumSize(new java.awt.Dimension(200, 80));
        setResizable(false);

        panelJViewer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelJViewer.setMaximumSize(new java.awt.Dimension(400, 400));
        panelJViewer.setMinimumSize(new java.awt.Dimension(200, 20));
        panelJViewer.setPreferredSize(new java.awt.Dimension(400, 160));
        panelJViewer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelJViewer, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(67, 43));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 38));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnClose.setMnemonic('S');
        btnClose.setText("Save");
        btnClose.setPreferredSize(new java.awt.Dimension(65, 23));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnClose);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
         this.setVisible(false);

}//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelJViewer;
    // End of variables declaration//GEN-END:variables

     
}
