/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dependents.java
 *
 * Created on Oct 31, 2010, 3:21:47 PM
 */
package com.jcl.payroll.ui;


import com.jcl.dbms.dbms;
import com.jcl.model.Employee;
import com.jcl.payroll.dtr.DailyTimeRecord;
import com.jcl.payroll.enumtypes.DTRType;
import com.jcl.payroll.enumtypes.FamilyRelationship;
import com.jcl.model.PaySlipDetail;
import com.jcl.utilities.MyDateFormatter;
import com.jcl.utilities.TransactionException;
import com.jcl.utils.SelectedButton;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author junald
 */
public class PaySlipEntry extends javax.swing.JDialog {

    public SelectedButton selectedButton = SelectedButton.Cancel;
    public PaySlipDetail psd;
    public SimpleDateFormat sdf2;
    public SimpleDateFormat stf;
    public Employee employee;

    /** Creates new form Dependents */
    public PaySlipEntry(java.awt.Frame parent, boolean modal, PaySlipDetail psd, Employee ee) {
        super(parent, modal);
        this.psd = psd;
        initComponents();
        employee = ee;
        sdf2 = MyDateFormatter.getDateTimeFormatter();
        stf = MyDateFormatter.getTimeFormatter2();

        for(DTRType dt: DTRType.values()){
            comboDTRType.addItem(dt.name());
        }
        labelCompleteName.setText(ee.getName());
        initScreen();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        panelDTR = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboDTRType = new javax.swing.JComboBox();
        labelName = new javax.swing.JLabel();
        labelCompleteName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JFormattedTextField();
        txtQuantity = new javax.swing.JFormattedTextField();
        txtLoaderCount = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JFormattedTextField();
        txtNotes = new javax.swing.JTextField();
        checkIsDeductable = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PaySlip Detail");
        setMinimumSize(new java.awt.Dimension(50, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(250, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(65, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        panelDTR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDTR.setMaximumSize(new java.awt.Dimension(250, 225));
        panelDTR.setMinimumSize(new java.awt.Dimension(250, 225));
        panelDTR.setPreferredSize(new java.awt.Dimension(250, 225));
        panelDTR.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel5, gridBagConstraints);

        comboDTRType.setNextFocusableComponent(txtAmount);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(comboDTRType, gridBagConstraints);

        labelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 3, 5);
        panelDTR.add(labelName, gridBagConstraints);

        labelCompleteName.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelCompleteName.setForeground(java.awt.Color.blue);
        labelCompleteName.setText("Lavador, Junald Conde");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 5);
        panelDTR.add(labelCompleteName, gridBagConstraints);

        jLabel1.setText("Amount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Quantity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Loader Count");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel3, gridBagConstraints);

        jLabel6.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(jLabel7, gridBagConstraints);

        txtAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####.##"))));
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAmount.setNextFocusableComponent(txtQuantity);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(txtAmount, gridBagConstraints);

        txtQuantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####.##"))));
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantity.setNextFocusableComponent(txtLoaderCount);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(txtQuantity, gridBagConstraints);

        txtLoaderCount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####.##"))));
        txtLoaderCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLoaderCount.setNextFocusableComponent(txtTotal);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(txtLoaderCount, gridBagConstraints);

        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####.00"))));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setNextFocusableComponent(txtNotes);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(txtTotal, gridBagConstraints);

        txtNotes.setText(" ");
        txtNotes.setNextFocusableComponent(btnSave);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        panelDTR.add(txtNotes, gridBagConstraints);

        checkIsDeductable.setText("Deductable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelDTR.add(checkIsDeductable, gridBagConstraints);

        getContentPane().add(panelDTR, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            selectedButton = SelectedButton.Save;
            saveScreen();
            this.setVisible(false);
        } catch (TransactionException ex) {
            Logger.getLogger(PaySlipEntry.class.getName()).log(Level.SEVERE, null, ex);
        
        } catch (Exception ex) {
            Logger.getLogger(PaySlipEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        selectedButton = SelectedButton.Cancel;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PaySlipEntry dialog = new PaySlipEntry(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkIsDeductable;
    private javax.swing.JComboBox comboDTRType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCompleteName;
    private javax.swing.JLabel labelName;
    private javax.swing.JPanel panelDTR;
    private javax.swing.JFormattedTextField txtAmount;
    private javax.swing.JFormattedTextField txtLoaderCount;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JFormattedTextField txtQuantity;
    private javax.swing.JFormattedTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void initScreen() {

        if(psd.isIsGenerated()){
            comboDTRType.setSelectedItem(psd.getPaySlipDetailType());
            comboDTRType.setEnabled(false);
            txtQuantity.setEditable(false);
            txtAmount.setEditable(false);
            txtLoaderCount.setEditable(false);
            txtTotal.setEditable(false);
            checkIsDeductable.setEnabled(false);
             btnSave.setEnabled(false);
        }



        txtNotes.setText(psd.getDescription());
        txtAmount.setValue(psd.getAmount());

        txtTotal.setValue(psd.getTotal());
        checkIsDeductable.setSelected(psd.isIsDeduction());

        if(psd.isIsProcess()){
             btnSave.setEnabled(false);
        }
        
         
    }

    private void saveScreen() throws TransactionException,  Exception {


        psd.setPaySlipDetailType(comboDTRType.getSelectedItem().toString());
        psd.setDescription(txtNotes.getText());
        psd.setAmount(Double.valueOf(txtAmount.getText()));        
        psd.setTotal(Double.valueOf(txtTotal.getText()));
        psd.setIsDeduction(checkIsDeductable.isSelected());

//        dbms.save(psd);
//        dbms.getDBInstance().ext().refresh(psd, Integer.MAX_VALUE);
    }
}
