/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApplicationSetting.java
 *
 * Created on Nov 5, 2010, 8:22:04 PM
 */
package com.jcl.settings.ui;


import com.jcl.main.MainApp;
import com.jcl.observables.PanelMessage;

/**
 *
 * @author junald
 */
public class ApplicationSetting extends javax.swing.JPanel {

    /** Creates new form ApplicationSetting */
    public ApplicationSetting() {
        initComponents();
           
        panelUser.add(new UserInformation());
        panelCompany.add(new CompanySettingInformation());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEmployee = new javax.swing.JPanel();
        panelUser = new javax.swing.JPanel();
        panelCompany = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelEmployee.setLayout(new javax.swing.BoxLayout(panelEmployee, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("Data", panelEmployee);

        panelUser.setLayout(new javax.swing.BoxLayout(panelUser, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("User", panelUser);

        panelCompany.setLayout(new javax.swing.BoxLayout(panelCompany, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane1.addTab("Company", panelCompany);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("System", jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTabbedPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        MainApp.messagePanelObservable.callObserver(new PanelMessage("Setting", "remove"));
    }//GEN-LAST:event_btnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelCompany;
    private javax.swing.JPanel panelEmployee;
    private javax.swing.JPanel panelUser;
    // End of variables declaration//GEN-END:variables
}
