/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeSettings.java
 *
 * Created on Nov 21, 2010, 9:10:43 PM
 */

package com.jcl.settings.ui;

 
import com.jcl.payroll.ui.PositionSetting;

/**
 *
 * @author junald
 */
public class OtherDataSettings extends javax.swing.JPanel {

    /** Creates new form EmployeeSettings */
    public OtherDataSettings() {
        initComponents();
        panelPosition.add(new PositionSetting());
      //  panelProductType.add(new ProductTypeSetting());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPosition = new javax.swing.JPanel();
        panelProductType = new javax.swing.JPanel();
        panelBranch = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelPosition.setBorder(javax.swing.BorderFactory.createTitledBorder("Position"));
        panelPosition.setLayout(new javax.swing.BoxLayout(panelPosition, javax.swing.BoxLayout.LINE_AXIS));
        add(panelPosition);

        panelProductType.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Group"));
        panelProductType.setLayout(new javax.swing.BoxLayout(panelProductType, javax.swing.BoxLayout.LINE_AXIS));
        add(panelProductType);

        panelBranch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout panelBranchLayout = new javax.swing.GroupLayout(panelBranch);
        panelBranch.setLayout(panelBranchLayout);
        panelBranchLayout.setHorizontalGroup(
            panelBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        panelBranchLayout.setVerticalGroup(
            panelBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        add(panelBranch);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBranch;
    private javax.swing.JPanel panelPosition;
    private javax.swing.JPanel panelProductType;
    // End of variables declaration//GEN-END:variables

}
